### ISSUE TITLE
Unable to install Cogulator

### ISSUE THREAD

**Issue by gmunatsi** [Cogulator/Cogulator#4]
![cogulator error](https://cloud.githubusercontent.com/assets/26121450/23625076/91113bae-02b0-11e7-8c99-6faf7aeb80e5.png)

**Comment by Tapestes** [comment]
Couple o' questions:
- What operating system?
- What version of Air do you have installed?
- Is this an upgrade or first time install?

Thanks,

Steven

**Comment by Tapestes** [comment]
Also, if you haven't already done so, uninstall and then reinstall Adobe Air and then try installing Cogulator.

**Comment by gmunatsi** [comment]
_What operating system?_ Windows 10
_What version of Air do you have installed?_ Version 24.0
_Is this an upgrade or first time install?_ First time install

**Comment by Tapestes** [comment]
Did some digging on what may be causing the issue.  Evidently, one of the most common reasons for this error on Windows is UAC.  From Adobe...
"This error can occur during installation if a standard or restricted user has turned off User Account Control (UAC) in Windows 7 or Window Vista. From Control Panel, Open UAC and enable it. A restart could be required. Once complete, retry the installation."

You can also try right-clicking on the cogulator.air file to see if an "install as administrator" option is presented. If so, you can try that as well.

Failing that, copy the Adobe AIR log file (C:\Users\user name\AppData\Local\Adobe\AIR\logs) and paste  the result here.  Because this is likely an Adobe/Windows issue, this one might be hard to run down. But, I'll help in any way I can.

**Comment by gmunatsi** [comment]
You were right, UAC was turned off. Turned it on. Restarted the pc and voila. thank you so much...

**Comment by Tapestes** [comment]
No problem.
